In [22]:
from numpy import array, random, dot
from random import choice

In [5]:
step_function = lambda x: 0 if x > 0 else 1

In [12]:
training_data = [
    (array([0, 0, 1]), 0),
    (array([0, 1, 1]), 1),
    (array([1, 0, 1]), 1),
    (array([1, 1, 1]), 1)
]

training_data

[(array([0, 0, 1]), 0),
 (array([0, 1, 1]), 1),
 (array([1, 0, 1]), 1),
 (array([1, 1, 1]), 1)]

In [11]:
w = random.rand(3)

w

array([0.07172412, 0.88814584, 0.10192754])

In [23]:
errors = []
learning_rate = 0.2
learning_iter = 100

1.0617974892601636

In [26]:
for i in range(learning_iter):
    x, expected = choice(training_data)
    result = dot(x, w)
    error = expected - step_function(result)
    errors.append(error)
    w += learning_rate * error * x

In [28]:
for x, _ in training_data:
    result = dot(x, w)
    print("{}: {} -> {}".format(x[:2], result, step_function(result)))

[0 0]: 29.90192753635056 -> 0
[0 1]: 50.190073373534034 -> 0
[1 0]: 50.37365165207653 -> 0
[1 1]: 70.66179748926001 -> 0


In [31]:
from pylab import plot, ylim
ylim([-1, 1])
plot(errors)

In [33]:
import numpy as np

In [35]:
np.divide([1, 2, 3], 3.0)

array([0.33333333, 0.66666667, 1.        ])

In [48]:
def softmax(L):
    return np.divide(np.exp(L), np.exp(L).sum())

In [49]:
softmax([5,6,7])

array([0.09003057, 0.24472847, 0.66524096])

In [51]:
P = [0.1, 0.3, 0.2]
np.log(P)

array([-2.30258509, -1.2039728 , -1.60943791])

In [52]:
Y = [1, 0, 0]
arr = np.float_(Y)

array([1., 0., 0.])

In [54]:
1.0 - arr

array([0., 1., 0.])

In [59]:
Y=np.float_([1,0,1,1])
Y

array([1., 0., 1., 1.])

In [60]:
1 - Y

array([0., 1., 0., 0.])